/*
hosttest/lutgen.c — generate the YM2612 lookup-table headers.

Compiles the vendored ym2612.c with GWENESIS_HOST_LUTGEN=1 (runtime tables
+ the original libm-based init_tables()), runs the initialization, and
emits gwenesis/sound/luts/{tl_tab,sin_tab,lfo_pm_table}.h as const arrays
placed in flash on the target (GW_IN_FLASH).

Usage:
    lutgen <luts-dir>            regenerate the three headers
    lutgen <luts-dir> --check    regenerate in memory and diff against the
                                 committed headers; exit 1 on mismatch
*/
#define GWENESIS_HOST_LUTGEN 1

#include "ym2612.c" /* found via -I gwenesis/sound */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Externs the included core expects the host to define. */
int16_t *gwenesis_ym2612_buffer;
int ym2612_index;
int ym2612_clock;

static char *emit_header(const char *name, const char *ctype,
                         const char *dims, const void *data, int count,
                         int is_unsigned, int elem_size)
{
    /* Build the header text in memory. */
    size_t cap = (size_t)count * 14 + 1024;
    char *buf = malloc(cap);
    size_t off = 0;

    off += snprintf(buf + off, cap - off,
                    "/* Generated by hosttest/lutgen — do not edit.\n"
                    "   Regenerate with: hosttest/build.sh lutgen && "
                    "hosttest/lutgen gwenesis/sound/luts */\n"
                    "static const %s GW_IN_FLASH %s%s = {\n",
                    ctype, name, dims);
    for (int i = 0; i < count; i++) {
        long v;
        if (elem_size == 1)
            v = is_unsigned ? (long)((const unsigned char *)data)[i]
                            : (long)((const signed char *)data)[i];
        else
            v = is_unsigned ? (long)((const unsigned int *)data)[i]
                            : (long)((const signed int *)data)[i];
        off += snprintf(buf + off, cap - off, "%ld,%s", v,
                        (i % 16 == 15) ? "\n" : "");
    }
    off += snprintf(buf + off, cap - off, "\n};\n");
    return buf;
}

static int write_or_check(const char *dir, const char *file, char *text,
                          int check)
{
    char path[1024];
    snprintf(path, sizeof(path), "%s/%s", dir, file);
    int rc = 0;
    if (check) {
        FILE *f = fopen(path, "rb");
        if (!f) {
            fprintf(stderr, "MISSING %s\n", path);
            rc = 1;
        } else {
            fseek(f, 0, SEEK_END);
            long sz = ftell(f);
            fseek(f, 0, SEEK_SET);
            char *disk = malloc(sz + 1);
            if (fread(disk, 1, sz, f) != (size_t)sz) sz = -1;
            fclose(f);
            if (sz != (long)strlen(text) || memcmp(disk, text, sz) != 0) {
                fprintf(stderr, "MISMATCH %s\n", path);
                rc = 1;
            } else {
                printf("OK %s\n", path);
            }
            free(disk);
        }
    } else {
        FILE *f = fopen(path, "wb");
        if (!f) {
            fprintf(stderr, "cannot write %s\n", path);
            rc = 1;
        } else {
            fwrite(text, 1, strlen(text), f);
            fclose(f);
            printf("wrote %s (%zu bytes)\n", path, strlen(text));
        }
    }
    free(text);
    return rc;
}

int main(int argc, char **argv)
{
    if (argc < 2) {
        fprintf(stderr, "usage: %s <luts-dir> [--check]\n", argv[0]);
        return 2;
    }
    const char *dir = argv[1];
    int check = argc > 2 && strcmp(argv[2], "--check") == 0;

    init_tables(); /* static function of the included ym2612.c */

    int rc = 0;
    rc |= write_or_check(dir, "tl_tab.h",
        emit_header("tl_tab", "signed int", "[13 * 2 * 256]",
                    tl_tab, TL_TAB_LEN, 0, 4), check);
    rc |= write_or_check(dir, "sin_tab.h",
        emit_header("sin_tab", "unsigned int", "[1024]",
                    sin_tab, SIN_LEN, 1, 4), check);
    rc |= write_or_check(dir, "lfo_pm_table.h",
        emit_header("lfo_pm_table", "UINT8", "[128 * 8 * 16]",
                    lfo_pm_table, 128 * 8 * 16, 1, 1), check);
    return rc;
}
